name: Deploy ADF to DEV

on:
  push:
    branches: [ "main" ]
    paths:
      - "adf_publish/**"
      - "parameterization/dev.parameters.json"
      - ".github/workflows/deploy-dev.yml"

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ARM template to DEV
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: rg-adf-dev
          template: adf_publish/ARMTemplateForFactory.json
          parameters: >
            @parameterization/dev.parameters.json
          failOnStdErr: false
